from pydantic import BaseModel, Field
from typing import Optional

import sys

sys.path.append("..")

from config import EmbeddingsConfig

embeddings_config = EmbeddingsConfig()


class Chunk(BaseModel):
    vector_id: str = Field(
        description="uuid string representing the id of the vector created."
    )
    vector: list[float] = Field(
        description="vector representing the text of the chunk."
    )
    metadata: dict[str, str] = Field(
        description="Dictionary with all the metadata generated by this service and the additional metadata provided."
    )


class EmbeddingRequest(BaseModel):
    text: str = Field(
        description="String with the whole text to be embedded", min_length=1
    )
    embedding_model_name: str = Field(
        default=embeddings_config.EMBEDDING_MODEL,
        min_length=1,
        description="Name of the embedding model. Must be available on SentenceTransformers.",
    )
    chunk_overlap: Optional[int] = Field(default=embeddings_config.CHUNK_OVERLAP, ge=0)
    metadata: Optional[dict[str, str]] = Field(
        default=None,
        description="Data associated to the text. Ex: {'title':'title_name', 'author':'author_name'}.",
    )


class EmbeddingResponse(BaseModel):
    chunks: list[Chunk]
