[project]
name = "rag-llm-energy-expert"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = []

[dependency-groups]
gcp = [
    "gcsfs>=2025.3.0",
    "google-cloud-run>=0.10.17",
    "google-cloud-secret-manager>=2.23.2",
    "google-cloud-storage>=3.1.0",
]
notebooks = [
    "dotenv>=0.9.9",
    "ipykernel>=6.29.5",
]
general-dev = [
    "loguru>=0.7.3",
    "pydantic>=2.10.6",
    "pydantic-settings>=2.8.1",
    "ruff>=0.11.0",
]
llm = [
    "litellm>=1.63.11",
    "pymupdf4llm>=0.0.17",
    "pypdf2>=3.0.1",
    "sentence-transformers>=3.4.1",
]
